INFO     log:logger_util.py:65 发送请求异常：异常信息: Traceback (most recent call last):
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 313, in send_request
    self.last_headers = self.replace_load(headers)
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

INFO     log:logger_util.py:65 分析YAML文件异常：异常信息: Traceback (most recent call last):
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 313, in send_request
    self.last_headers = self.replace_load(headers)
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 185, in analysis_yaml
    res = self.send_request(name =name,method=method,
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 336, in send_request
    error_log("发送请求异常：异常信息: %s" % str(traceback.format_exc()))
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\logger_util.py", line 66, in error_log
    raise Exception(log_message)
Exception: 发送请求异常：异常信息: Traceback (most recent call last):
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 313, in send_request
    self.last_headers = self.replace_load(headers)
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\requests_util.py", line 140, in replace_load
    new_value = getattr(DubugTalk(), func_name)(*args_value.split(','))
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\debug_talk.py", line 26, in get_extract_data
    return read_extract_file(node_name)
  File "D:\CMS2.0_API\EOS_API_AUTOMATION_TEST\common\yaml_util.py", line 19, in read_extract_file
    return value[one_node]
TypeError: 'NoneType' object is not subscriptable